friendcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('friends/', views.friends_index, name='index'),
    path('friends/<int:friend_id>/', views.friends_detail, name='detail'),
    path('friends/create/', views.FriendCreate.as_view(), name='friends_create'),
    path('friends/<int:pk>/update/',
         views.FriendUpdate.as_view(), name='friends_update'),
    path('friends/<int:pk>/delete/',
         views.FriendDelete.as_view(), name='friends_delete'),
    path('friends/<int:friend_id>/add_meeting/',
         views.add_meeting, name='add_meeting'),
    path('memories/', views.MemoryList.as_view(), name='memories_index'),
    path('memories/<int:pk>/', views.MemoryDetail.as_view(), name='memories_detail'),
    path('memories/create/', views.MemoryCreate.as_view(), name='memories_create'),
    path('memories/<int:pk>/update/',
         views.MemoryUpdate.as_view(), name='memories_update'),
    path('memories/<int:pk>/delete/',
         views.MemoryDelete.as_view(), name='memories_delete'),
    path('friends/<int:friend_id>/assoc_memory/<int:memory_id>/',
         views.assoc_memory, name='assoc_memory'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

EVENTS = (
    ('H', 'Hangout'),
    ('M', 'Meal'),
    ('S', 'Special Occassion'),
)


class Memory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    year = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('memories_detail', kwargs={'pk': self.id})


class Friend(models.Model):
    name = models.CharField(max_length=100)
    ethnicity = models.CharField(max_length=100)
    height = models.CharField(max_length=100)
    age = models.IntegerField()
    memories = models.ManyToManyField(Memory)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'friend_id': self.id})


class Meeting(models.Model):
    date = models.DateField('Meeting Date')
    event = models.CharField(
        max_length=1,
        choices=EVENTS,
        default=EVENTS[0][0]
    )

    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_event_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Meeting


class MeetingForm(ModelForm):
    class Meta:
        model = Meeting
        fields = ['date', 'event']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Friend, Memory
from .forms import MeetingForm


# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def friends_index(request):
    friends = Friend.objects.all()
    return render(request, 'friends/index.html', {'friends': friends})


def friends_detail(request, friend_id):
    friend = Friend.objects.get(id=friend_id)
    memories_not_assoc_w_friend = Memory.objects.exclude(
        id__in=friend.memories.all().values_list('id'))
    meeting_form = MeetingForm()
    return render(request, 'friends/detail.html', {
        'friend': friend, 'meeting_form': meeting_form,
        'memories': memories_not_assoc_w_friend
    })


class FriendCreate(CreateView):
    model = Friend
    fields = ['name', 'ethnicity', 'height', 'age']
    succes_url = '/friends/'


class FriendUpdate(UpdateView):
    model = Friend
    fields = ['ethnicity', 'height', 'age']


class FriendDelete(DeleteView):
    model = Friend
    success_url = '/friends/'


def add_meeting(request, friend_id):
    form = MeetingForm(request.POST)
    if form.is_valid():
        new_meeting = form.save(commit=False)
        new_meeting.friend_id = friend_id
        new_meeting.save()
    return redirect('detail', friend_id=friend_id)


def assoc_memory(request, friend_id, memory_id):
    Friend.objects.get(id=friend_id).memories.add(memory_id)
    return redirect('detail', friend_id=friend_id)


class MemoryList(ListView):
    model = Memory


class MemoryDetail(DetailView):
    model = Memory


class MemoryCreate(CreateView):
    model = Memory
    fields = '__all__'


class MemoryUpdate(UpdateView):
    model = Memory
    fields = ['name', 'description', 'year']


class MemoryDelete(DeleteView):
    model = Memory
    success_url = '/memories/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Logger</h1>
<hr />
<p>Hire the Friend Logger!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Friend Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;FriendLogger</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'memories_create' %}">Add A Memory</a></li>
            <li><a href="{% url 'memories_index' %}">View All Memories</a></li>
            <li><a href="{% url 'friends_create' %}">Add a Friend</a></li>
            <li><a href="{% url 'index' %}"">View All My Friends</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2020 Friend Logger &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/friends/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Friend Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ friend.name }}</span>
        <p>Ethnicity: {{ friend.ethnicity }}</p>
        <p>Height: {{ friend.height }}</p>
        {% if friend.age > 0 %}
        <p>Age: {{ friend.age }}</p>
        {% else %}
        <p>Age: Baby</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'friends_update' friend.id %}">Edit</a>
        <a href="{% url 'friends_delete' friend.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_meeting' friend.id %}" method="post">
      {% csrf_token %} {{ meeting_form.as_p }}
      <input type="submit" class="btn" value="Add Meeting" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Event</th>
        </tr>
      </thead>
      <tbody>
        {% for meeting in friend.meeting_set.all %}
        <tr>
          <td>{{meeting.date}}</td>
          <td>{{meeting.get_event_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h3>Memories with {{ friend.name }}:</h3>
    {% if friend.memories.count %} {% for memory in friend.memories.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{memory.name}} in {{memory.year}} </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Memories :/</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>All Memories</h3>
    {% if memories.count %} {% for memory in memories.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{memory.name}} in {{memory.year}} </span>
      </div>
      <div class="card-action">
        <form
          action="{% url 'assoc_memory' friend.id memory.id %}"
          method="post"
        >
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{memory.name}} No More Memories!</h5>
    {% endif %}
  </div>
</div>
<script>
  const dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
  const selectEl = document.getElementById("id_event");
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/friends/index.html
{% extends 'base.html' %} {% block content %}

<h1>Friends List</h1>

{% for friend in friends %}
<div class="card">
  <a href="{% url 'detail' friend.id %}">
    <div class="card-content">
      <span class="card-title">{{ friend.name }}</span>
      <p>Ethnicity: {{ friend.ethnicity }}</p>
      <p>Height: {{ friend.height }}</p>
      {% if friend.age > 0 %}
      <p>Age: {{ friend.age }}</p>
      {% else %}
      <p>Age: Baby</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/friend_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Friend</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' friend.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/friend_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Friend</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/memory_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Memory</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'memories_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/memory_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Memory Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ memory.name }}</span>
        <p>Description: {{ memory.description }}</p>
        <p>Year: {{ memory.year }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'memories_update' memory.id %}">Edit</a>
        <a href="{% url 'memories_delete' memory.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/memory_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Memory</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/memory_list.html
{% extends 'base.html' %} {% block content %}

<h1>Memory List</h1>

{% for memory in memory_list %}
<a href="{% url 'memories_detail' memory.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ memory.name }}</span>
      <p>Description: {{ memory.description }}</p>
      <p>Year: {{ memory.year }}</p>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}